# Generated by Django 6.0.4 on 2026-04-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='encrypted_private_key',
            field=models.TextField(blank=True, null=True, verbose_name='Shifrlangan yopiq kalit (Encrypted RSA Private Key)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='public_key',
            field=models.TextField(blank=True, null=True, verbose_name='Ochiq kalit (RSA Public Key)'),
        ),
    ]
