# Generated by Django 6.0.4 on 2026-04-28 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Hujjat nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsifi')),
                ('file', models.FileField(upload_to='encrypted_docs/', verbose_name='Shifrlangan fayl')),
                ('sha256_hash', models.CharField(max_length=64, verbose_name='SHA-256 Xesh')),
                ('privacy_level', models.CharField(choices=[('simple', 'Oddiy'), ('protected', 'Himoyalangan')], default='simple', max_length=20, verbose_name='Maxfiylik darajasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Hujjat egasi')),
            ],
        ),
    ]
