# Generated by Django 6.0.4 on 2026-05-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='sha256_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='SHA-256 Xesh'),
        ),
    ]
