# Generated by Django 6.0.4 on 2026-04-28 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Tizimga kirdi'), ('logout', 'Tizimdan chiqdi'), ('upload', 'Hujjat yukladi'), ('request', "Hujjat so'radi"), ('approve', 'Tasdiqladi'), ('reject', 'Rad etdi'), ('download', 'Hujjatni ochdi/yuklab oldi')], max_length=20, verbose_name='Bajarilgan amal')),
                ('details', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumotlar")),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
    ]
