# Generated by Django 6.0.4 on 2026-04-28 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('share_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='1-ulush (Baza uchun)')),
                ('share_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='2-ulush (Receiver uchun)')),
                ('share_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='3-ulush (Approver uchun)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_shares', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlovchi')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document', verbose_name='Hujjat')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
            ],
        ),
    ]
