# Generated by Django 6.0.4 on 2026-05-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentshare',
            name='share_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='share_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
