# Generated by Django 6.0.4 on 2026-05-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_alter_documentshare_share_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentshare',
            name='share_1',
            field=models.TextField(blank=True, null=True, verbose_name='1-ulush (Baza uchun)'),
        ),
    ]
